import { Item } from '../models/index.model';

export const data: Item[] = [
  {
    url: 'prime-build-lab',
    name: 'Prime build Lab',
    logo: '/assets/images/portfolio/prime/logo.png',
    title: ['page.portfolio.prime.title.t1'],
    services: [
      'page.portfolio.prime.services.s1',
      'page.portfolio.prime.services.s2',
      'page.portfolio.prime.services.s3',
      'page.portfolio.prime.services.s4',
    ],
    photos: [
      '/assets/images/portfolio/prime/1.png',
      '/assets/images/portfolio/prime/2.jpg',
      '/assets/images/portfolio/prime/3.jpg',
      '/assets/images/portfolio/prime/4.jpg',
      '/assets/images/portfolio/prime/5.jpg',
      '/assets/images/portfolio/prime/6.jpg',
      '/assets/images/portfolio/prime/7.jpg',
      '/assets/images/portfolio/prime/8.jpg',
    ],
  },
  {
    url: 'la-clean',
    name: 'La Clean',
    logo: '/assets/images/portfolio/laclean/logo.png',
    title: ['page.portfolio.clean.title.t1'],
    services: [
      'page.portfolio.clean.services.s1',
      'page.portfolio.clean.services.s2',
      'page.portfolio.clean.services.s3',
      'page.portfolio.clean.services.s4',
    ],
    photos: [
      '/assets/images/portfolio/laclean/1.png',
      '/assets/images/portfolio/laclean/2.png',
      '/assets/images/portfolio/laclean/3.png',
      '/assets/images/portfolio/laclean/6.png',
      '/assets/images/portfolio/laclean/7.png',
      '/assets/images/portfolio/laclean/8.png',
      '/assets/images/portfolio/laclean/4.png',
      '/assets/images/portfolio/laclean/5.png',
    ],
  },
  {
    url: 'wine',
    name: 'WinehundredMiles | Wine ',
    logo: '/assets/images/portfolio/wine/logo.png',
    title: ['page.portfolio.wine.title.t1'],
    services: [
      'page.portfolio.wine.services.s1',
      'page.portfolio.wine.services.s2',
    ],
    photos: [
      '/assets/images/portfolio/wine/1.png',
      '/assets/images/portfolio/wine/2.png',
      '/assets/images/portfolio/wine/4.png',
      '/assets/images/portfolio/wine/5.png',
      '/assets/images/portfolio/wine/6.png',
      '/assets/images/portfolio/wine/7.png',
    ],
  },
  {
    url: 'caselab',
    name: 'Caselab | Legal Firm',
    logo: '/assets/images/portfolio/caselab/logo.png',
    title: ['page.portfolio.case.title.t1', 'page.portfolio.case.title.t2'],
    services: ['page.portfolio.case.services.s1'],
    photos: [
      '/assets/images/portfolio/caselab/4.jpg',
      '/assets/images/portfolio/caselab/2.png',
      '/assets/images/portfolio/caselab/3.jpg',
      '/assets/images/portfolio/caselab/1.png',
      '/assets/images/portfolio/caselab/6.png',
      '/assets/images/portfolio/caselab/8.jpg',
      '/assets/images/portfolio/caselab/7.jpg',
    ],
  },
  {
    url: 'construction',
    name: 'Construction company',
    logo: '/assets/images/portfolio/construction/logo.png',
    title: ['page.portfolio.construct.title.t1'],
    services: ['page.portfolio.construct.services.s1'],
    photos: [
      '/assets/images/portfolio/construction/1.png',
      '/assets/images/portfolio/construction/2.png',
      '/assets/images/portfolio/construction/3.png',
    ],
  },
  {
    url: 'hair',
    name: 'Hair extension studio',
    logo: '/assets/images/portfolio/hair/logo.png',
    title: ['page.portfolio.hair.title.t1'],
    services: [
      'page.portfolio.hair.services.s1',
      'page.portfolio.hair.services.s2',
    ],
    photos: [
      '/assets/images/portfolio/hair/1.png',
      '/assets/images/portfolio/hair/2.png',
      '/assets/images/portfolio/hair/3.png',
      '/assets/images/portfolio/hair/4.png',
    ],
  },
  {
    url: 'instagram',
    name: 'Instagram pages',
    logo: '/assets/images/portfolio/instagram/logo.png',
    title: ['page.portfolio.instagram.title.t1'],
    services: [
      'page.portfolio.instagram.services.s1',
      'page.portfolio.instagram.services.s2',
    ],
    photos: [
      '/assets/images/portfolio/instagram/1.png',
      '/assets/images/portfolio/instagram/2.png',
      '/assets/images/portfolio/instagram/5.png',
      '/assets/images/portfolio/instagram/4.png',
      '/assets/images/portfolio/instagram/3.png',
    ],
  },
  {
    url: 'web',
    name: 'Web design work',
    logo: '/assets/images/portfolio/web/logo.png',
    title: ['page.portfolio.web.title.t1'],
    services: [
      'page.portfolio.web.services.s1',
      'page.portfolio.web.services.s2',
    ],
    photos: [
      '/assets/images/portfolio/web/1.png',
      '/assets/images/portfolio/web/2.png',
      '/assets/images/portfolio/web/3.png',
      '/assets/images/portfolio/web/4.png',
      '/assets/images/portfolio/web/5.png',
      '/assets/images/portfolio/web/6.png',
      '/assets/images/portfolio/web/7.png',
      '/assets/images/portfolio/web/8.png',
      '/assets/images/portfolio/web/9.png',
      '/assets/images/portfolio/web/10.png',
    ],
  },
  {
    url: 'pol',
    name: 'Pol.dok ',
    logo: '/assets/images/portfolio/pol/logo.png',
    title: ['page.portfolio.poldok.title.t1'],
    services: [
      'page.portfolio.poldok.services.s1',
      'page.portfolio.poldok.services.s2',
      'page.portfolio.poldok.services.s3',
      'page.portfolio.poldok.services.s4',
      'page.portfolio.poldok.services.s5',
      'page.portfolio.poldok.services.s6',
    ],
    photos: [
      '/assets/images/portfolio/pol/4.png',
      '/assets/images/portfolio/pol/5.png',
      '/assets/images/portfolio/pol/7.jpg',
      '/assets/images/portfolio/pol/1.png',
      '/assets/images/portfolio/pol/2.png',
    ],
  },
  {
    url: 'polsza',
    name: 'Polsza.info',
    logo: '/assets/images/portfolio/polsza/logo.png',
    title: ['page.portfolio.polsza.title.t1'],
    services: [
      'page.portfolio.polsza.services.s1',
      'page.portfolio.polsza.services.s2',
      'page.portfolio.polsza.services.s3',
    ],
    photos: [
      '/assets/images/portfolio/polsza/1.png',
      '/assets/images/portfolio/polsza/2.png',
      '/assets/images/portfolio/polsza/3.png',
    ],
  },
  {
    url: 'expert',
    name: 'Expert photo ',
    logo: '/assets/images/portfolio/expert/logo.png',
    title: ['page.portfolio.expert.title.t1'],
    services: [
      'page.portfolio.expert.services.s1',
      'page.portfolio.expert.services.s2',
      'page.portfolio.expert.services.s3',
      'page.portfolio.expert.services.s4',
      'page.portfolio.expert.services.s5',
    ],
    photos: [
      '/assets/images/portfolio/expert/1.png',
      '/assets/images/portfolio/expert/2.png',
      '/assets/images/portfolio/expert/3.png',
    ],
  },
  {
    url: 'creative',
    name: 'Creative photo ',
    logo: '/assets/images/portfolio/creative/logo.png',
    title: ['page.portfolio.creative.title.t1'],
    services: [
      'page.portfolio.creative.services.s1',
      'page.portfolio.creative.services.s2',
    ],
    photos: [
      '/assets/images/portfolio/creative/1.png',
      '/assets/images/portfolio/creative/2.png',
      '/assets/images/portfolio/creative/3.png',
    ],
  },
  {
    url: 'thematic',
    name: 'Thematic photo',
    logo: '/assets/images/portfolio/thematic/logo.png',
    title: ['page.portfolio.thema.title.t1'],
    services: [
      'page.portfolio.thema.services.s1',
      'page.portfolio.thema.services.s2',
    ],
    photos: [
      '/assets/images/portfolio/thematic/1.png',
      '/assets/images/portfolio/thematic/2.png',
      '/assets/images/portfolio/thematic/3.png',
    ],
  },
  {
    url: 'homewear',
    name: 'Homewear for women',
    logo: '/assets/images/portfolio/homewear/logo.png',
    title: ['page.portfolio.homewear.title.t1'],
    services: [
      'page.portfolio.homewear.services.s1',
      'page.portfolio.homewear.services.s2',
    ],
    photos: [
      '/assets/images/portfolio/homewear/1.png',
      '/assets/images/portfolio/homewear/2.png',
      '/assets/images/portfolio/homewear/3.png',
    ],
  },
  {
    url: 'sky',
    name: 'SKYBIZ Services',
    logo: '/assets/images/portfolio/sky/logo.png',
    title: ['page.portfolio.sky.title.t1'],
    services: ['page.portfolio.sky.services.s1'],
    photos: [
      '/assets/images/portfolio/sky/1.png',
      '/assets/images/portfolio/sky/2.png',
      '/assets/images/portfolio/sky/3.png',
      '/assets/images/portfolio/sky/4.png',
      '/assets/images/portfolio/sky/5.png',
      '/assets/images/portfolio/sky/6.png',
      '/assets/images/portfolio/sky/7.png',
      '/assets/images/portfolio/sky/8.png',
      '/assets/images/portfolio/sky/9.png',
      '/assets/images/portfolio/sky/10.png',
    ],
  },
];
